name: dependencies

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.2.5
  google_fonts: ^6.3.2
  flutter_screenutil: ^5.9.3
  animate_gradient: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0