name: portfolio

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  dependencies:
  common:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
